kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Developer
  namespace: dev # TODO: Re-run this file with other necessary ns
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Developer
  namespace: prod # TODO: Re-run this file with other necessary ns
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Developer
  namespace: staging # TODO: Re-run this file with other necessary ns
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: DeveloperBinding
  namespace: dev # TODO: Re-run this file with other necessary ns, match with role above
subjects:
- kind: User 
  name: Joey
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: Developer
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: DeveloperBinding
  namespace: staging # TODO: Re-run this file with other necessary ns, match with role above
subjects:
- kind: User 
  name: Joey
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: Developer
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: DeveloperBinding
  namespace: prod # TODO: Re-run this file with other necessary ns, match with role above
subjects:
- kind: User 
  name: Joey
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: Developer
  apiGroup: rbac.authorization.k8s.io
---